import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { sendEmail } from '@/lib/email';
import { logAudit } from '@/lib/audit';

export async function POST(req: Request) {
  try {
    const payload = await req.json();
    const {
      client_id,
      invoice_number,
      month_year,
      description,
      amount,
      gst_rate,
      gst_amount,
      total_amount,
      issued_date,
      due_date,
      payment_method,
      notes,
      send_email,
    } = payload;

    if (!client_id || !invoice_number || !amount) {
      return NextResponse.json({ error: 'Missing required invoice parameters' }, { status: 400 });
    }

    const supabase = await createClient();

    // 1. Get client name & email for notifications
    const { data: client, error: clientErr } = await supabase
      .from('clients')
      .select('name, email')
      .eq('id', client_id)
      .single();

    if (clientErr || !client) {
      return NextResponse.json({ error: 'Client not found' }, { status: 404 });
    }

    // 1a. Generate invoice number atomically
    let finalInvoiceNumber = invoice_number;
    const isAutoGenerated = invoice_number.startsWith('VG-') && /VG-\d{4}-\d+/.test(invoice_number);

    if (isAutoGenerated) {
      const { data: nextCounter, error: rpcError } = await supabase.rpc('get_next_invoice_counter');
      if (rpcError) {
        throw rpcError;
      }
      const year = new Date().getFullYear();
      const padded = String(nextCounter).padStart(3, '0');
      finalInvoiceNumber = `VG-${year}-${padded}`;
    } else {
      const { error: rpcError } = await supabase.rpc('get_next_invoice_counter');
      if (rpcError) {
        console.error('Error incrementing counter for custom invoice:', rpcError);
      }
    }

    // 2. Insert Invoice
    const { data: invoice, error: invoiceErr } = await supabase
      .from('invoices')
      .insert({
        client_id,
        invoice_number: finalInvoiceNumber,
        month_year,
        description,
        amount,
        gst_rate,
        gst_amount,
        total_amount,
        status: 'pending',
        issued_date,
        due_date,
        payment_method,
        notes,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (invoiceErr) {
      throw invoiceErr;
    }

    // 4. Log to activity_log
    const { data: { user } } = await supabase.auth.getUser();
    await supabase.from('activity_log').insert({
      user_id: user?.id || null,
      client_id,
      action: 'invoice_created',
      entity_type: 'invoice',
      entity_id: invoice.id,
      title: `Invoice ${finalInvoiceNumber} generated`,
      description: `Invoice worth ₹${total_amount} raised for ${client.name}.`,
    });

    // 4a. Immutable system audit log
    await logAudit({
      userId: user?.id || null,
      action: 'INSERT',
      tableName: 'invoices',
      recordId: invoice.id,
      newValues: invoice,
      request: req,
    });

    // 4b. Notify all admins — new invoice created
    const { data: admins } = await supabase.from('profiles').select('id').eq('role', 'admin');
    if (admins && admins.length > 0) {
      const notifs = admins.map((a) => ({
        user_id: a.id,
        type: 'invoice_created',
        title: `🧾 Invoice ${finalInvoiceNumber} raised`,
        message: `New invoice for ${client.name}: ₹${Number(total_amount).toLocaleString('en-IN')} — due ${due_date || 'on receipt'}.`,
        link: `/dashboard/finance`,
        is_read: false,
        priority: 'low',
      }));
      await supabase.from('notifications').insert(notifs);
    }

    // 5. Optionally send email via shared email utility
    if (send_email && client.email) {
      const formattedTotal = new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR',
        maximumFractionDigits: 0,
      }).format(total_amount);

      await sendEmail({
        to: client.email,
        subject: `Invoice Raised: ${invoice_number}`,
        html: `
          <h2>New Invoice Raised</h2>
          <p>Dear ${client.name},</p>
          <p>A new invoice has been raised for your active digital marketing services:</p>
          <ul>
            <li><strong>Invoice Number:</strong> ${invoice_number}</li>
            <li><strong>Description:</strong> ${description || 'Digital Marketing Services'}</li>
            <li><strong>Amount Due:</strong> ${formattedTotal}</li>
            <li><strong>Due Date:</strong> ${due_date ? new Date(due_date).toLocaleDateString('en-IN') : 'Upon receipt'}</li>
          </ul>
          <p>You can view, download, or pay this invoice inside your Client Portal at <a href="https://portal.veloxisglobal.com">portal.veloxisglobal.com</a>.</p>
          <p>Thank you for partnering with Veloxis Global!</p>
          <br />
          <p>Warm regards,</p>
          <p><strong>Finance Department</strong></p>
          <p>${process.env.RESEND_FROM_NAME || 'Veloxis Global'}</p>
        `,
      });
    }

    return NextResponse.json({ success: true, invoice });
  } catch (err) {
    console.error('Invoice generation API error:', err);
    return NextResponse.json({ error: err instanceof Error ? err.message : 'Failed to generate invoice' }, { status: 500 });
  }
}
